-- Create the contacts table
create table public.contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  subject text not null,
  message text not null
);

-- Enable Row Level Security (RLS)
alter table public.contacts enable row level security;

-- Create a policy to allow anyone (anon) to insert data
create policy "Enable insert for everyone" 
on public.contacts 
for insert 
to anon 
with check (true);

-- Create a policy to allow only service role (admin) to view data
-- This prevents public users from reading the submitted contacts
create policy "Enable read access for service role only" 
on public.contacts 
for select 
to service_role 
using (true);
